/**
 * B2SHARE API
 * EUDAT B2SHARE API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package eudat.b2share.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import eudat.b2share.model.FileDetailInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * Metadata
 */

public class Metadata   {
  @JsonProperty("record_id")
  private BigDecimal recordId = null;

  @JsonProperty("open_access")
  private Boolean openAccess = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("domain")
  private String domain = null;

  @JsonProperty("discipline")
  private List<String> discipline = new ArrayList<String>();

  @JsonProperty("contributors")
  private List<String> contributors = new ArrayList<String>();

  @JsonProperty("creator")
  private List<String> creator = new ArrayList<String>();

  @JsonProperty("date")
  private String date = null;

  @JsonProperty("pid")
  private String pid = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("file_url")
  private String fileUrl = null;

  @JsonProperty("licence")
  private String licence = null;

  @JsonProperty("publication_date")
  private String publicationDate = null;

  @JsonProperty("language_code")
  private String languageCode = null;

  @JsonProperty("language")
  private String language = null;

  @JsonProperty("publisher")
  private String publisher = null;

  @JsonProperty("project_name")
  private String projectName = null;

  @JsonProperty("quality")
  private String quality = null;

  @JsonProperty("region")
  private String region = null;

  @JsonProperty("version")
  private String version = null;

  @JsonProperty("contact_email")
  private String contactEmail = null;

  @JsonProperty("alternate_identifier")
  private String alternateIdentifier = null;

  @JsonProperty("keywords")
  private String keywords = null;

  @JsonProperty("embargo_till")
  private String embargoTill = null;

  /**
   * Gets or Sets lingResourceType
   */
  public enum LingResourceTypeEnum {
    TEXT("Text"),
    
    IMAGE("Image"),
    
    VIDEO("Video"),
    
    AUDIO("Audio"),
    
    TIME_SERIES("Time-Series"),
    
    OTHER("Other");

    private String value;

    LingResourceTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @JsonProperty("ling_resource_type")
  private List<LingResourceTypeEnum> lingResourceType = new ArrayList<LingResourceTypeEnum>();

  /**
   * Gets or Sets resourceType
   */
  public enum ResourceTypeEnum {
    TEXT("Text"),
    
    IMAGE("Image"),
    
    VIDEO("Video"),
    
    AUDIO("Audio"),
    
    TIME_SERIES("Time-Series"),
    
    OTHER("Other");

    private String value;

    ResourceTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @JsonProperty("resource_type")
  private List<ResourceTypeEnum> resourceType = new ArrayList<ResourceTypeEnum>();

  @JsonProperty("filea")
  private List<FileDetailInfo> filea = new ArrayList<FileDetailInfo>();

  public Metadata recordId(BigDecimal recordId) {
    this.recordId = recordId;
    return this;
  }

   /**
   * .
   * @return recordId
  **/
  @ApiModelProperty(example = "null", value = ".")
  public BigDecimal getRecordId() {
    return recordId;
  }

  public void setRecordId(BigDecimal recordId) {
    this.recordId = recordId;
  }

  public Metadata openAccess(Boolean openAccess) {
    this.openAccess = openAccess;
    return this;
  }

   /**
   * .
   * @return openAccess
  **/
  @ApiModelProperty(example = "null", value = ".")
  public Boolean getOpenAccess() {
    return openAccess;
  }

  public void setOpenAccess(Boolean openAccess) {
    this.openAccess = openAccess;
  }

  public Metadata title(String title) {
    this.title = title;
    return this;
  }

   /**
   * .
   * @return title
  **/
  @ApiModelProperty(example = "null", required = true, value = ".")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Metadata description(String description) {
    this.description = description;
    return this;
  }

   /**
   * .
   * @return description
  **/
  @ApiModelProperty(example = "null", required = true, value = ".")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Metadata domain(String domain) {
    this.domain = domain;
    return this;
  }

   /**
   * .
   * @return domain
  **/
  @ApiModelProperty(example = "null", value = ".")
  public String getDomain() {
    return domain;
  }

  public void setDomain(String domain) {
    this.domain = domain;
  }

  public Metadata discipline(List<String> discipline) {
    this.discipline = discipline;
    return this;
  }

   /**
   * .
   * @return discipline
  **/
  @ApiModelProperty(example = "null", value = ".")
  public List<String> getDiscipline() {
    return discipline;
  }

  public void setDiscipline(List<String> discipline) {
    this.discipline = discipline;
  }

  public Metadata contributors(List<String> contributors) {
    this.contributors = contributors;
    return this;
  }

   /**
   * .
   * @return contributors
  **/
  @ApiModelProperty(example = "null", value = ".")
  public List<String> getContributors() {
    return contributors;
  }

  public void setContributors(List<String> contributors) {
    this.contributors = contributors;
  }

  public Metadata creator(List<String> creator) {
    this.creator = creator;
    return this;
  }

   /**
   * .
   * @return creator
  **/
  @ApiModelProperty(example = "null", value = ".")
  public List<String> getCreator() {
    return creator;
  }

  public void setCreator(List<String> creator) {
    this.creator = creator;
  }

  public Metadata date(String date) {
    this.date = date;
    return this;
  }

   /**
   * .
   * @return date
  **/
  @ApiModelProperty(example = "null", value = ".")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public Metadata pid(String pid) {
    this.pid = pid;
    return this;
  }

   /**
   * .
   * @return pid
  **/
  @ApiModelProperty(example = "null", value = ".")
  public String getPid() {
    return pid;
  }

  public void setPid(String pid) {
    this.pid = pid;
  }

  public Metadata email(String email) {
    this.email = email;
    return this;
  }

   /**
   * .
   * @return email
  **/
  @ApiModelProperty(example = "null", value = ".")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Metadata fileUrl(String fileUrl) {
    this.fileUrl = fileUrl;
    return this;
  }

   /**
   * .
   * @return fileUrl
  **/
  @ApiModelProperty(example = "null", value = ".")
  public String getFileUrl() {
    return fileUrl;
  }

  public void setFileUrl(String fileUrl) {
    this.fileUrl = fileUrl;
  }

  public Metadata licence(String licence) {
    this.licence = licence;
    return this;
  }

   /**
   * .
   * @return licence
  **/
  @ApiModelProperty(example = "null", value = ".")
  public String getLicence() {
    return licence;
  }

  public void setLicence(String licence) {
    this.licence = licence;
  }

  public Metadata publicationDate(String publicationDate) {
    this.publicationDate = publicationDate;
    return this;
  }

   /**
   * .
   * @return publicationDate
  **/
  @ApiModelProperty(example = "null", value = ".")
  public String getPublicationDate() {
    return publicationDate;
  }

  public void setPublicationDate(String publicationDate) {
    this.publicationDate = publicationDate;
  }

  public Metadata languageCode(String languageCode) {
    this.languageCode = languageCode;
    return this;
  }

   /**
   * .
   * @return languageCode
  **/
  @ApiModelProperty(example = "null", required = true, value = ".")
  public String getLanguageCode() {
    return languageCode;
  }

  public void setLanguageCode(String languageCode) {
    this.languageCode = languageCode;
  }

  public Metadata language(String language) {
    this.language = language;
    return this;
  }

   /**
   * .
   * @return language
  **/
  @ApiModelProperty(example = "null", value = ".")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public Metadata publisher(String publisher) {
    this.publisher = publisher;
    return this;
  }

   /**
   * .
   * @return publisher
  **/
  @ApiModelProperty(example = "null", value = ".")
  public String getPublisher() {
    return publisher;
  }

  public void setPublisher(String publisher) {
    this.publisher = publisher;
  }

  public Metadata projectName(String projectName) {
    this.projectName = projectName;
    return this;
  }

   /**
   * .
   * @return projectName
  **/
  @ApiModelProperty(example = "null", value = ".")
  public String getProjectName() {
    return projectName;
  }

  public void setProjectName(String projectName) {
    this.projectName = projectName;
  }

  public Metadata quality(String quality) {
    this.quality = quality;
    return this;
  }

   /**
   * .
   * @return quality
  **/
  @ApiModelProperty(example = "null", value = ".")
  public String getQuality() {
    return quality;
  }

  public void setQuality(String quality) {
    this.quality = quality;
  }

  public Metadata region(String region) {
    this.region = region;
    return this;
  }

   /**
   * .
   * @return region
  **/
  @ApiModelProperty(example = "null", value = ".")
  public String getRegion() {
    return region;
  }

  public void setRegion(String region) {
    this.region = region;
  }

  public Metadata version(String version) {
    this.version = version;
    return this;
  }

   /**
   * .
   * @return version
  **/
  @ApiModelProperty(example = "null", value = ".")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public Metadata contactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
    return this;
  }

   /**
   * .
   * @return contactEmail
  **/
  @ApiModelProperty(example = "null", value = ".")
  public String getContactEmail() {
    return contactEmail;
  }

  public void setContactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
  }

  public Metadata alternateIdentifier(String alternateIdentifier) {
    this.alternateIdentifier = alternateIdentifier;
    return this;
  }

   /**
   * .
   * @return alternateIdentifier
  **/
  @ApiModelProperty(example = "null", value = ".")
  public String getAlternateIdentifier() {
    return alternateIdentifier;
  }

  public void setAlternateIdentifier(String alternateIdentifier) {
    this.alternateIdentifier = alternateIdentifier;
  }

  public Metadata keywords(String keywords) {
    this.keywords = keywords;
    return this;
  }

   /**
   * .
   * @return keywords
  **/
  @ApiModelProperty(example = "null", value = ".")
  public String getKeywords() {
    return keywords;
  }

  public void setKeywords(String keywords) {
    this.keywords = keywords;
  }

  public Metadata embargoTill(String embargoTill) {
    this.embargoTill = embargoTill;
    return this;
  }

   /**
   * .
   * @return embargoTill
  **/
  @ApiModelProperty(example = "null", value = ".")
  public String getEmbargoTill() {
    return embargoTill;
  }

  public void setEmbargoTill(String embargoTill) {
    this.embargoTill = embargoTill;
  }

  public Metadata lingResourceType(List<LingResourceTypeEnum> lingResourceType) {
    this.lingResourceType = lingResourceType;
    return this;
  }

   /**
   * .
   * @return lingResourceType
  **/
  @ApiModelProperty(example = "null", required = true, value = ".")
  public List<LingResourceTypeEnum> getLingResourceType() {
    return lingResourceType;
  }

  public void setLingResourceType(List<LingResourceTypeEnum> lingResourceType) {
    this.lingResourceType = lingResourceType;
  }

  public Metadata resourceType(List<ResourceTypeEnum> resourceType) {
    this.resourceType = resourceType;
    return this;
  }

   /**
   * .
   * @return resourceType
  **/
  @ApiModelProperty(example = "null", value = ".")
  public List<ResourceTypeEnum> getResourceType() {
    return resourceType;
  }

  public void setResourceType(List<ResourceTypeEnum> resourceType) {
    this.resourceType = resourceType;
  }

  public Metadata filea(List<FileDetailInfo> filea) {
    this.filea = filea;
    return this;
  }

   /**
   * Get filea
   * @return filea
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<FileDetailInfo> getFilea() {
    return filea;
  }

  public void setFilea(List<FileDetailInfo> filea) {
    this.filea = filea;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Metadata metadata = (Metadata) o;
    return Objects.equals(this.recordId, metadata.recordId) &&
        Objects.equals(this.openAccess, metadata.openAccess) &&
        Objects.equals(this.title, metadata.title) &&
        Objects.equals(this.description, metadata.description) &&
        Objects.equals(this.domain, metadata.domain) &&
        Objects.equals(this.discipline, metadata.discipline) &&
        Objects.equals(this.contributors, metadata.contributors) &&
        Objects.equals(this.creator, metadata.creator) &&
        Objects.equals(this.date, metadata.date) &&
        Objects.equals(this.pid, metadata.pid) &&
        Objects.equals(this.email, metadata.email) &&
        Objects.equals(this.fileUrl, metadata.fileUrl) &&
        Objects.equals(this.licence, metadata.licence) &&
        Objects.equals(this.publicationDate, metadata.publicationDate) &&
        Objects.equals(this.languageCode, metadata.languageCode) &&
        Objects.equals(this.language, metadata.language) &&
        Objects.equals(this.publisher, metadata.publisher) &&
        Objects.equals(this.projectName, metadata.projectName) &&
        Objects.equals(this.quality, metadata.quality) &&
        Objects.equals(this.region, metadata.region) &&
        Objects.equals(this.version, metadata.version) &&
        Objects.equals(this.contactEmail, metadata.contactEmail) &&
        Objects.equals(this.alternateIdentifier, metadata.alternateIdentifier) &&
        Objects.equals(this.keywords, metadata.keywords) &&
        Objects.equals(this.embargoTill, metadata.embargoTill) &&
        Objects.equals(this.lingResourceType, metadata.lingResourceType) &&
        Objects.equals(this.resourceType, metadata.resourceType) &&
        Objects.equals(this.filea, metadata.filea);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recordId, openAccess, title, description, domain, discipline, contributors, creator, date, pid, email, fileUrl, licence, publicationDate, languageCode, language, publisher, projectName, quality, region, version, contactEmail, alternateIdentifier, keywords, embargoTill, lingResourceType, resourceType, filea);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Metadata {\n");
    
    sb.append("    recordId: ").append(toIndentedString(recordId)).append("\n");
    sb.append("    openAccess: ").append(toIndentedString(openAccess)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    discipline: ").append(toIndentedString(discipline)).append("\n");
    sb.append("    contributors: ").append(toIndentedString(contributors)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    pid: ").append(toIndentedString(pid)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    fileUrl: ").append(toIndentedString(fileUrl)).append("\n");
    sb.append("    licence: ").append(toIndentedString(licence)).append("\n");
    sb.append("    publicationDate: ").append(toIndentedString(publicationDate)).append("\n");
    sb.append("    languageCode: ").append(toIndentedString(languageCode)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    publisher: ").append(toIndentedString(publisher)).append("\n");
    sb.append("    projectName: ").append(toIndentedString(projectName)).append("\n");
    sb.append("    quality: ").append(toIndentedString(quality)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    contactEmail: ").append(toIndentedString(contactEmail)).append("\n");
    sb.append("    alternateIdentifier: ").append(toIndentedString(alternateIdentifier)).append("\n");
    sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
    sb.append("    embargoTill: ").append(toIndentedString(embargoTill)).append("\n");
    sb.append("    lingResourceType: ").append(toIndentedString(lingResourceType)).append("\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    filea: ").append(toIndentedString(filea)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

